/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/
var skycons = new Skycons();

  // you can add a icon to a html canvas. simply supply its element id and the weather you want to show.
  /*skycons.add("today", Skycons.PARTLY_CLOUDY_DAY);
  skycons.add("day1", Skycons.CLEAR_DAY);
  skycons.add("day2", Skycons.CLOUDY);
  skycons.add("day3", Skycons.RAIN);*/

  var todaySkycon;
  var day1Skycon;
  var day2Skycon;
  var day3Skycon;



  // update a icon on  canvas by its id
 // skycons.set("today", Skycons.PARTLY_CLOUDY_NIGHT);

  /*
  Get value from Bootstrap dropdown menu
  */
  
  $("#dropdown li").on('click', function(){
      var chosenCity = $(this).text().slice(0,3);
      alert(chosenCity);
      $("#navBtn").text(chosenCity);
      getWeatherData(chosenCity);
  });

  function getWeatherData(city){
    console.log(city)
    var apiUrl = "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22" + city + "%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
    console.log(apiUrl);        
    $.getWeatherJSON(apiUrl, function(data){
      console.log(data);
      console.log(data.query.results.channel.title);
      var today = data.query.results.channel.lastBuildDate.slice(5,16);
      $(".date").text(today); 
      console.log(today);
      var weather = data.query.results.channel.item.forecast[1].text;
      $(".weather").text(weather); 
      console.log(weather);
      var nowTemp = data.query.results.channel.item.condition.temp;
      $(".temperature").text( Math.round( (nowTemp-32)*5/9 ) );
      console.log(nowTemp);
      var day1 = data.query.results.channel.item.forecast[1].date;
      $("th.day1").text(day1);
      console.log(day1);
      var day2 = data.query.results.channel.item.forecast[2].date;
      $("th.day2").text(day2);
      console.log(day2);
      var day3 = data.query.results.channel.item.forecast[3].date;
      $("th.day3").text(day3);
      console.log(day3);        
      var day1weather = data.query.results.channel.item.forecast[1].text;
      console.log(day1weather);
      var day2weather = data.query.results.channel.item.forecast[2].text;
      console.log(day2weather);
      var day3weather = data.query.results.channel.item.forecast[3].text;
      console.log(day3weather);
      var day1HighTemp = data.query.results.channel.item.forecast[1].high;
      $("#day1HighTemp").text( Math.round( (day1HighTemp-32)*5/9 ) );
      console.log(day1HighTemp);
      var day2HighTemp = data.query.results.channel.item.forecast[2].high;
      $("#day2HighTemp").text( Math.round( (day2HighTemp-32)*5/9 ) );
      console.log(day2HighTemp);
      var day3HighTemp = data.query.results.channel.item.forecast[3].high;
      $("#day3HighTemp").text( Math.round( (day3HighTemp-32)*5/9 ) );
      console.log(day3HighTemp);
      var day1LowTemp = data.query.results.channel.item.forecast[1].low;
      $("#day1LowTemp").text( Math.round( (day1LowTemp-32)*5/9 ) );
      console.log(day1LowTemp);
      var day2LowTemp = data.query.results.channel.item.forecast[2].low;
      $("#day2LowTemp").text( Math.round( (day2LowTemp-32)*5/9 ) );
      console.log(day2LowTemp);
      var day3LowTemp = data.query.results.channel.item.forecast[3].low;
      $("#day3LowTemp").text( Math.round( (day3LowTemp-32)*5/9 ) );
      console.log(day3LowTemp);
      console.log("today",weather,todaySkycon);
      skycons.set("today", getIcon(weather));
      skycons.set("day1", getIcon(day1weather));
      skycons.set("day2", getIcon(day2weather));
      skycons.set("day3", getIcon(day3weather));

    });

  }
  getWeatherData("臺北市");

  function getIcon(weather){
    if( weather.indexOf("Sunny") >= 0 ){
      return Skycons.CLEAR_DAY;
    }else if( weather == "Clear (night)" ){
      return    Skycons.CLEAR_NIGHT;
    }else if( weather.indexOf("Cloudy") >= 0 ){
      return    Skycons.CLOUDY;
    }else if(  weather.indexOf("Showers") >= 0  || weather.indexOf("Rain") >= 0 || weather.indexOf("Thunderstorms") >= 0 ){
      return    Skycons.RAIN;
    }else if( weather == "Sleet" ){1
      return    Skycons.SLEET;
    }else if( weather.indexOf("Snow") >= 0 ){
      return    Skycons.SNOW;
    }else if( weather == "Wind" || weather.indexOf("Breezy") >= 0 ){
      return    Skycons.WIND;
    }else if( weather == "Foggy" ){
      return    Skycons.FOG;
    }

  }   

  // start all icons animation!
  skycons.play();     

function getTemps(){
  var $dropdown = $("#dropdown li");
  $dropdown.each(function(index,element){
    var city = $(element).text().slice(0,3);
    var apiUrl = "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22" + city + "%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
    $.getWeatherJSON(apiUrl, function(data){
      var nowTemp = data.query.results.channel.item.condition.temp;
      $(element).children('a').children('span').text( Math.round( (nowTemp-32)*5/9 ) +"℃");
      $(".navTemp").css("float", "right");
    })
  }) 
}
getTemps();


